language: java
sudo: required

jdk:
  - openjdk8
  - oraclejdk8
  - openjdk11
  - oraclejdk11
os:
  - linux

dist: trusty

install:
  - curl https://raw.githubusercontent.com/italiangrid/build-settings/master/maven/cnaf-mirror-settings.xml -o $HOME/.m2/settings.xml
